name: Build NVIDIA Helper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout our files
        uses: actions/checkout@v4

      - name: Download NVIDIA NVAPI
        uses: actions/checkout@v4
        with:
          repository: NVIDIA/nvapi
          path: nvapi

      - name: Build helper
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Compile helper
        shell: cmd
        run: |
          cl /nologo /EHsc /O2 ^
            /I nvapi ^
            main.cpp ^
            /link /OUT:NvDisplaySetup.exe nvapi\x64\nvapi64.lib

      - name: Upload helper
        uses: actions/upload-artifact@v4
        with:
          name: NvDisplaySetup
          path: NvDisplaySetup.exe
